theme="material-design"
baseurl = "http://albush.com"
languageCode = "en-us"
title = "Alan Bush's Blog"
MetaDataFormat = "toml"
paginate = 6 # To specify a multiple of 3
# disqusShortname = "Your Disqus Name" # optional
copyright = "Â© 2015 Alan Bush"

[author]
  author = "Alan Bush"
  email = "al@albush.com"

[params]
  description = "Mustachioed Cloud Technology Mentor by day; Daddy, Husband and Improvisor by night." # optional
  twitter = "alanbush" # optional
  github = "albush" # optional
  # facebook = "Your facebook Name" # optional
  gplus = "AlanBush" # optional
  linkedin = "adbush" # optional
  about = "about"
  headerCover = "http://share.albush.com/fyKF4BgPAO/background.jpg" # optional
  footerCover = "http://drops.albush.com/background-cover.jpg" # optional

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[podcasts]
  description = "Educating and inspiring the cloud computing community."
  image = "http://drops.albush.com/ooh-square.png"
  headerCover = "http://drops.albush.com/RAX%20CLOUD%20OFFICE%20HANGOUT%20FINAL.png"
